inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Metrics/AbcSize:
  Max: 25

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
